### ISSUE TITLE
Implement New Header Design

### ISSUE THREAD

**Issue by SirajChokshi** [hack4impact-uiuc/falling-fruit#181]
## Description

The header has be redesigned to be more condensed and feature rich.

## Learning objectives

- Styling
- Using global styles
- Accessability
- Semantic HTML

## Todo

- [ ] Edit existing header
- [ ] Add new styles
- [ ] Add dropdown menu

## Useful links

Design:
https://www.figma.com/file/Ry8tCDzQmtpOAsKMOjuqGS/Falling-Fruit?node-id=2353%3A3336
