### ISSUE TITLE
Data Table Component

### ISSUE THREAD

**Issue by SirajChokshi** [hack4impact-uiuc/falling-fruit#182]
## Description

Implement a table that can display sortable columns and rows of data.

## Learning objectives

- Choosing libraries that play well with the codebase
- Styling logic-heavy, vendor components

## Todo

- [x] Choose a React table component that:
   - Has all the features we need (sortable, pagination, filtering, search)
   - Works well with `styled-components`
- [x] Wrap the component from the package
- [x] Decide on a configuration and which options/props should be passed through the wrapper
- [x] Style the table to match the mockup

## Useful links

- Design on Figma: https://www.figma.com/file/Ry8tCDzQmtpOAsKMOjuqGS/Falling-Fruit?node-id=2362%3A3889
- Ask Siraj questions about the design/design decisions
