### ISSUE TITLE
Create Template for Building Pages

### ISSUE THREAD

**Issue by SirajChokshi** [hack4impact-uiuc/falling-fruit#188]
## Description

Create a new file for pages (you can make an example page to use a sandbox for testing components you make). Write styles for this file so that we can make pages like [About](https://fallingfruit.org/about) and [Data](https://fallingfruit.org/data?c=forager%2Cfreegan&locale=en).

## Learning objectives

- Learning to design a system for other engineers (e.g. Ethan) to build out feature-rich pages
- Styling
- Media queries
- Routing with React-Router

## Todo

- [ ] Create styles for basic page elements (`p`, `h1` to `h4`, a PhotoGrid, etc)
    - Your page should be able to house the data table #183
    - Look into how you can reuse the [existing photo grid](https://github.com/hack4impact-uiuc/falling-fruit/blob/c6ab9685326d4807043e3c5d4a9c48abe86d8579/src/components/entry/PhotoGrid.js)
    - Make sure to use media queries to implement the mobile side of the Figma design!
- [ ] Thoroughly test each component and make sure they are responsive
- [ ] Make links on header bar route to a few new pages (About, etc.)
    - Find out where to add the pages (which existing component has the `<Switch>`?)
    

## Useful links

- Design on Figma: https://www.figma.com/file/Ry8tCDzQmtpOAsKMOjuqGS/Falling-Fruit?node-id=2353%3A3278
- React Router documentation: https://reactrouter.com/web/guides/quick-start
- Ask Siraj questions about the UI design/design decisions

**Comment by Qrtn** [comment]
Make sure to use media queries to implement the mobile side of the Figma design!

**Comment by Qrtn** [comment]
Resolved by #199
Resolved by #186
