### ISSUE TITLE
Authentication state & integration

### ISSUE THREAD

**Issue by Qrtn** [hack4impact-uiuc/falling-fruit#190]
## Description

We need to prepare our app to handle authentication.

This involves:
- Creating "async thunk action creators" in Redux for logging in and logging out. These thunks get the token from the API
- When logging in and out, persist/remove the token from a persistent form of storage, in addition to the Redux store.
  - There will be a "Remember Me" checkbox on the login page.
  - Depending on whether this is checked, what has to be different about how you store the token?

Note that this issue does not include the UI for logging in/out.

## Learning objectives

- Researching and designing the best possible approach to integrate an app-wide construct into its architecture
- How authentication works with JWT
- Using Redux as a state management tool for information that concerns the entire app
- `localStorage` and `sessionStorage`

## Todo

- [x] Read through all the links below
- [x] Re-read this issue
- [x] Feel free to do additional reading (articles, examples) on how to approach designing this system
- [x] Create your own plan (a list of todos) and add them to the pull request in a reply for me to review
- [x] After I look over it, start implementing

## Useful links

- https://jwt.io/introduction
- https://redux.js.org/faq/miscellaneous#how-can-i-implement-authentication-in-redux
  - Please note that we're using a library called Redux Toolkit, which can handle many things for you.
  - Be sure to get an understanding of what Redux Toolkit provides (links below) before diving in.
- https://redux.js.org/tutorials/essentials/part-1-overview-concepts
- https://redux.js.org/tutorials/essentials/part-5-async-logic
  - In particular, note the `createAsyncThunk` API.
- Users API from https://petstore.swagger.io/?url=https://fallingfruit.org/test-api/0.3/openapi.yml
- https://redux-toolkit.js.org/usage/usage-guide

## Other links
- https://egghead.io/lessons/javascript-redux-persisting-the-state-to-the-local-storage
- https://dev.to/link2twenty/react-redux-and-localstorage-2lih
- https://redux-toolkit.js.org/usage/usage-guide#asynchronous-logic-and-data-fetching
