### ISSUE TITLE
Location Information View

### ISSUE THREAD

**Issue by rxun** [hack4impact-uiuc/falling-fruit#24]
## Description
The location information view displays all the information about a particular location. This includes information on the location itself, as well as the type of edible, and the particular edible (whether or not it is ripe, etc). Locations can be reviewed, edited, and reported. Locations also have an option to "teleport" to their address. 

## Objectives
- [x] *P0*: Users should be able to click on a pin on the map then navigate to this mini view so they can get more information about the location they're interested in.
- [x] *P0*: Users should be able to navigate to the location's address on the map view so they can view the location in relation to other map objects.
- [x] *P0*: Users should be able to read more about the particular location and associated edible, as well as other metadata so they can learn details about a location.
- [ ] *P0*: Users should be able to edit a location that they wrote so they can make appropriate updates or corrections on a location.
- [x] *P1*: Users should be able to click on a list location and then navigate to this mini view so they can access information on a location they're interested in.
- [x] *P1*: Users should be able to read through reviews of a location so they can get other people's opinions on the location and edible.

## Todo / Backlog
-

**Comment by ezwelty** [comment]
The location view looks really slick. The only issue I see is that the design does not currently support multiple types. This goes for both the common name title and scientific name subtitle (how should this look if there are multiple types) and the "Other Resources" section, which when there are multiple types could have multiple e.g. "Wikipedia" URLs, one for each type. 

There will most likely be a page for each type eventually, and the "Other Resources" can be moved there, but this still means that the title/subtitle view needs to be amended to support multiple types and each type needs to be clickable.

When loading a location from a URL (e.g. https://falling-fruit.vercel.app/entry/3383), the location info is populated but the map remains at the default global view. It should probably be zoomed in and centered on the location, and the location placemark on the map should be highlighted in some way (e.g. halo).

Let me know if this is a good place for this feedback, or if you would prefer I open separate issues for each of these.

**Comment by Qrtn** [comment]
Closed by #32, and various other improvements. We still need to zoom in on the location when loading it from a URL. This will be resolved in a future PR that also implements the ability to share the map viewport in the link independently of the selected entry. (Very similar to Google Maps)
