### ISSUE TITLE
Location Form

### ISSUE THREAD

**Issue by rxun** [hack4impact-uiuc/falling-fruit#51]
## Description
The location form allows users to submit a new location to pin on the map. Please check Figmas for most recently updated user flows + designs, as well as the [Feature Spec Doc](https://docs.google.com/document/d/1IgJHD5zaEB_81YF-zPeaPRSLb5_aWWbMMdQs6dd9XtQ/edit#) for a detailed user flow and field explanations. 

The main parts of the user flow include:

1. The user can click on the **floating "+" button** that appears on map view. This will lead them to the first part of the form (desktop: left sidebar, mobile: new separate page).
2. The first part is **marker placement**. By default, the marker is at the "current location" of the user (whether that's their actual current location or the last address they've searched). On mobile, the marker is static in the middle of the screen and the user can move the map around it. On desktop, you can click and place the pin. Confirming on mobile and placing the pin on desktop will both update the "current address" field in the form.
3. The **default info screen**. This should include types, position, description, and photo. 
4. The **optional info screen**. This should include season, access status, and verification. This only exists on a separate screen in mobile.
5. The **optional visit screen**. Documenting a location doesn’t necessarily mean that you had visited at the time. For this reason, you have to submit a separate review form that documents your visit -- this is done on desktop, currently, through embedding the second form within the first if you click a checkbox. The optional visit screen will essentially be the review form, but it will not be the same review form that is used on the location information page. This only exists on a separate screen in mobile.
6. The last part is the **confirmation screen**. They should be able to view all of the information they've inputted, then click submit if they're satisfied. 
7. After submitting the form, the user should automatically navigate to the new location and open up the **entry details page** they just made!

## Objectives
- [ ] *P1*: Users should be able to fill out the location form with relevant information about the types observed, and then submit it so it shows up in both Map and List View. 
- [ ] *P1*: Users should be able to have the default address of the location as the center of the map they are on for ease of access.
- [ ] *P1*: Users should be able to move the address marker and confirm it on the form submission (in mobile) so they can easily pin their location. This location should also yield the semantic description of the coordinates.
- [ ] *P1*: Users should be able to review and confirm all the details of their submission before submitting and be permitted to go back and edit any section they want to correct. 
- [ ] *P1*: User should be able to navigate to their newly create entry details page after submitting their location. 

## Todo / Backlog
-

**Comment by ezwelty** [comment]
This looks great. The only thing I would add is that the marker placement mode should probably use the satellite map layer, since trees and other landscape details are visible in that view.
