### ISSUE TITLE
[TBD] List View 

### ISSUE THREAD

**Issue by rxun** [hack4impact-uiuc/falling-fruit#54]
## Description
A complement to the map view, the list view will display locations in a list format, making it easier to easily skim and find types. This is especially important for accessibility reasons, and the desktop version does _not_ currently have a list view.

Please check Figmas for most recently updated user flows + designs (and the [feature specification doc](https://docs.google.com/document/d/1IgJHD5zaEB_81YF-zPeaPRSLb5_aWWbMMdQs6dd9XtQ/edit#heading=h.sq4fw9julrxt) for any other information). 

## Objectives
- [ ] *P1*: Users should be able to switch tabs to the list view to view a list of nearby locations (to the center of the map).
- [ ] *P1*: Users should be able to open up a location's details page to get more info on the location, then click back to go back to the list view. 
- [ ] *P1*: Users should be able to filter by both address and multiple types in mobile, similar to the desktop version.
- [ ] *P2*: Users should be able to filter by other factors (including verification, etc) on the desktop version for more precise sorting. 

## Todo / Backlog
-

**Comment by ezwelty** [comment]
One important consideration is whether the map and list view should share the same API endpoint and response. It will be faster and (I suspect) simpler for both views to share the same location data. The downside to this strategy is that the e.g. nearest X locations needed for the list view will look odd on the map view in areas where there are many more locations available: as a tight cluster of locations at the center of the map. Two potential solutions: a message in map view like "X of Y locations (zoom in for more)" or a bounding box (greying out the rest of the map?) displayed around the X locations when X != Y.

**Comment by Qrtn** [comment]
Resolved by #82 and #90.
